package com.rewardculture.model;

/**
 * The user model. For now this only includes two fields: userId is the Uuid generated by the Firebase
 * authentication service and ostId is the uuid generated by SimpleToken. userId is also used as
 * the username in ostid.
 */
public class User {

    private String userId;
    private String ostId;

    public User() {

    }

    public User(String uid, String ostId) {
        this.userId = uid;
        this.ostId = ostId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getOstId() {
        return ostId;
    }

    public void setOstId(String ostId) {
        this.ostId = ostId;
    }

    @Override
    public String toString() {
        return String.format("(%s, %s, %s)", userId, ostId);
    }
}
